@startuml sequenceDiagramViewMember
!define DARKBLUE
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml
actor User
User <- MenuView : getinputAction()
activate MenuView
User --> MenuView : input
MenuView -> EditMemberView : register()
deactivate MenuView
activate EditMemberView
EditMemberView -> User : requireInput()
User --> EditMemberView : answer
EditMemberView -> Member : setName(answer)
activate Member

EditMemberView -> User : requireInput()
User --> EditMemberView : answer
EditMemberView -> Member : setPersonalNumber(answer)
deactivate Member
EditMemberView -> BaseView : notifyMemberCreated()
deactivate EditMemberView
activate BaseView

BaseView ->o RegisterController : IViewObserver.onMemberCreated(member)

deactivate BaseView
RegisterController -> SavedState : setMember(member)
activate RegisterController
RegisterController -> BaseController : addToInstanceState(currentState)
deactivate RegisterController
activate BaseController
BaseController -> SavedInstaceState : addState(state)
BaseController -> BaseController : writeToDB()
database JSON
BaseController -> JSON : savedInstanceState
deactivate BaseController


@enduml