@startuml sequenceDiagramViewMember
!define DARKBLUE
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml
actor User

User -> MenuView : getinputAction()
activate MenuView
MenuView -> BaseView : isMemberVerified()
activate BaseView
User <- BaseView : RequireInput()
User --> BaseView  : input
BaseView -> RegisterController : hasIdSavedState(input)
deactivate BaseView
activate RegisterController
RegisterController --> MenuView : verification

alt member is Verified
    MenuView -> MemberInfoView : ViewMember()
    deactivate MenuView
    activate MemberInfoView
    MemberInfoView -> RegisterController : getMember()
    
    
    RegisterController -> SavedState : getMember()
    activate SavedState
    SavedState --> RegisterController : member
    deactivate SavedState
    RegisterController --> MemberInfoView : member
    deactivate RegisterController
    MemberInfoView -> User : show info
    deactivate MemberInfoView

else verified = false
    activate RegisterController
    RegisterController -> User : Show error
    deactivate RegisterController
end
@enduml